name: Continuous Integration & Delivery

on:
  push:
    branches: [ develop, master, bugfix/*, feature/* ]
  pull_request:
    branches: [ develop, master ]
  workflow_dispatch:
    inputs:
      publish_nuget_package:
        description: Publish a new NuGet package?
        required: false
        type: boolean

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  TZ: CET # https://stackoverflow.com/q/53510011

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          clean: true
          lfs: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v2

      - name: Restore .NET Tools
        run: dotnet tool restore

      - name: Restore NuGet Packages
        run: dotnet cake --target=Restore-NuGet-Packages

      - name: Run Build
        run: dotnet cake --target=Build

      - name: Run Tests
        run: dotnet cake --target=Tests --test-filter=FullyQualifiedName~${{ startsWith(matrix.os, 'ubuntu') && 'DotNet.Testcontainers' || 'DotNet.Testcontainers.Tests.Unit.Containers.Windows' }}

      - name: Get Logs
        run: Get-ChildItem -Path . -Include *.log -Recurse | % { Get-Content -Path $_.FullName }
        shell: pwsh
        if: always()

      - name: Rename Test And Coverage Results
        run: Get-ChildItem -Path 'test-coverage' -Filter *.xml | Rename-Item -NewName { $_.Name -Replace 'coverage', '${{ matrix.os }}'.ToLower() }
        shell: pwsh

      - name: Upload Test And Coverage Results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: |
            test-coverage
            test-results

  publish:
    if: ${{ contains(fromJson('["develop", "master"]'), github.ref_name) }}

    needs: build

    environment: production

    runs-on: ubuntu-20.04

    env:
      FEED_SOURCE: https://api.nuget.org/v3/index.json
      FEED_APIKEY: ${{ secrets.FEED_APIKEY }}
      SONARCLOUD_URL: https://sonarcloud.io
      SONARCLOUD_ORGANIZATION: testcontainers
      SONARCLOUD_KEY: testcontainers_testcontainers-dotnet
      SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          clean: true
          lfs: true
          fetch-depth: 0

      - name: Download Test And Coverage Results (ubuntu-20.04)
        uses: actions/download-artifact@v4.1.7
        with:
          name: ubuntu-20.04

      - name: Download Test And Coverage Results (windows-2019)
        uses: actions/download-artifact@v4.1.7
        with:
          name: windows-2019

      - name: Fix Absolute Code Coverage Paths
        run: |
          Get-ChildItem -Path 'test-coverage' -Filter *.xml | % { (Get-Content $_) -Replace '[A-Za-z0-9:\-\/\\]+src', '${{ github.workspace }}/src' | Set-Content $_ }
          Get-ChildItem -Path 'test-coverage' -Filter *.xml | % { (Get-Content $_) -Replace '[A-Za-z0-9:\-\/\\]+tests', '${{ github.workspace }}/tests' | Set-Content $_ }
        shell: pwsh

      - name: Setup .NET
        uses: actions/setup-dotnet@v2

      - name: Restore .NET Tools
        run: dotnet tool restore

      - name: Restore NuGet Packages
        run: dotnet cake --target=Restore-NuGet-Packages

      - name: Run Sonar Analysis
        run: dotnet cake --target=Sonar-Begin

      - name: Run Build
        run: dotnet cake --target=Build

      - name: Upload Sonar Results
        run: dotnet cake --target=Sonar-End

      - name: Publish NuGet Package
        run: dotnet cake --target=Publish
        env:
          PUBLISH_NUGET_PACKAGE: ${{ inputs.publish_nuget_package }}
